#ifndef ERROR_CODES_H
#define ERROR_CODES_H

/**
 * Error Codes for the BMS SAFE System
 * Used for comprehensive error handling
 */
enum class ErrorCode {
  SUCCESS = 0,
  
  // Authentication Errors
  AUTH_INVALID_PASSWORD = 100,
  AUTH_INVALID_USER_ID,
  AUTH_MASTER_NOT_VERIFIED,
  AUTH_USER_NOT_VERIFIED,
  AUTH_FINGERPRINT_NOT_FOUND,
  AUTH_FINGERPRINT_ERROR,
  AUTH_TIMEOUT_EXPIRED,
  
  // User Management Errors
  USER_NOT_FOUND = 200,
  USER_ALREADY_EXISTS,
  USER_INVALID_ID,
  USER_PASSWORD_TOO_SHORT,
  USER_PASSWORD_TOO_LONG,
  USER_MOBILE_INVALID,
  
  // Door Control Errors
  DOOR_SENSOR_NOT_ALIGNED = 300,
  DOOR_OPEN_TIMEOUT,
  DOOR_CLOSE_TIMEOUT,
  DOOR_ACCESS_DENIED_HOLIDAY,
  DOOR_ACCESS_DENIED_TIME_SLOT,
  DOOR_ALREADY_OPEN,
  DOOR_ALREADY_CLOSED,
  
  // Holiday Management Errors
  HOLIDAY_NOT_FOUND = 400,
  HOLIDAY_ALREADY_EXISTS,
  HOLIDAY_INVALID_DATE,
  HOLIDAY_STORAGE_FULL,
  
  // EEPROM Errors
  EEPROM_READ_ERROR = 500,
  EEPROM_WRITE_ERROR,
  EEPROM_ADDRESS_OUT_OF_RANGE,
  EEPROM_DATA_CORRUPTED,
  
  // GSM Errors
  GSM_NOT_INITIALIZED = 600,
  GSM_SEND_FAILED,
  GSM_QUEUE_FULL,
  GSM_MODULE_ERROR,
  
  // SMS Command Errors
  SMS_INVALID_COMMAND = 700,
  SMS_INVALID_PARAMETERS,
  SMS_MISSING_PARAMETERS,
  SMS_MOBILE_NOT_REGISTERED,
  
  // System Errors
  SYSTEM_NOT_INITIALIZED = 800,
  SYSTEM_MEMORY_LOW,
  SYSTEM_HARDWARE_ERROR
};

/**
 * Helper function to get error message
 */
const char* getErrorMessage(ErrorCode code);

#endif // ERROR_CODES_H

